compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: ds_config.json
  deepspeed_moe_layer_cls_names: ''
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 0
mixed_precision: fp16