
sbatch -J=dino --err=slurm/main/dino_cpu.err --out=slurm/main/dino_cpu.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10
sbatch -J=dino --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/dino_gpu.err --out=slurm/main/dino_gpu.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --reward_fn dino   --per_prompt_stat_tracking_buffer_size 10

sbatch -J=dino --err=slurm/main/dino_cpu_inv.err --out=slurm/main/dino_cpu_inv.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --reward_fn dino   --per_prompt_stat_tracking_buffer_size 10
sbatch -J=dino --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/dino_gpu_inv.err --out=slurm/main/dino_gpu_inv.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10

sbatch -J=dino --err=slurm/main/dino_cpu_inv_multi.err --out=slurm/main/dino_cpu_inv_multi.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10
sbatch -J=dino --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/dino_gpu_inv_multi.err --out=slurm/main/dino_gpu_inv_multi.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10


sbatch -J=dino --err=slurm/main/dino_cpu_inv_pp.err --out=slurm/main/dino_cpu_inv_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10
sbatch -J=dino --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/dino_gpu_inv_pp.err --out=slurm/main/dino_gpu_inv_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10
 
sbatch -J=dino --err=slurm/main/dino_cpu_inv_multi_pp.err --out=slurm/main/dino_cpu_inv_multi_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10
sbatch -J=dino --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/dino_gpu_inv_multi_pp.err --out=slurm/main/dino_gpu_inv_multi_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn dino --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --reward_fn dino  --per_prompt_stat_tracking_buffer_size 10

