
sbatch -J=qualiclip --err=slurm/main/qualiclip_cpu.err --out=slurm/main/qualiclip_cpu.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --reward_fn qualiclip --evil_twin
sbatch -J=qualiclip --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/qualiclip_gpu.err --out=slurm/main/qualiclip_gpu.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --reward_fn qualiclip --evil_twin

sbatch -J=qualiclip --err=slurm/main/qualiclip_cpu_inv.err --out=slurm/main/qualiclip_cpu_inv.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --reward_fn qualiclip --evil_twin
sbatch -J=qualiclip --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/qualiclip_gpu_inv.err --out=slurm/main/qualiclip_gpu_inv.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --reward_fn qualiclip --evil_twin

sbatch -J=qualiclip --err=slurm/main/qualiclip_cpu_inv_multi.err --out=slurm/main/qualiclip_cpu_inv_multi.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --reward_fn qualiclip --evil_twin
sbatch -J=qualiclip --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/qualiclip_gpu_inv_multi.err --out=slurm/main/qualiclip_gpu_inv_multi.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --reward_fn qualiclip --evil_twin


sbatch -J=qualiclip --err=slurm/main/qualiclip_cpu_inv_pp.err --out=slurm/main/qualiclip_cpu_inv_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --reward_fn qualiclip --evil_twin
sbatch -J=qualiclip --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/qualiclip_gpu_inv_pp.err --out=slurm/main/qualiclip_gpu_inv_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --reward_fn qualiclip --evil_twin
 
sbatch -J=qualiclip --err=slurm/main/qualiclip_cpu_inv_multi_pp.err --out=slurm/main/qualiclip_cpu_inv_multi_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --reward_fn qualiclip --evil_twin
sbatch -J=qualiclip --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/qualiclip_gpu_inv_multi_pp.err --out=slurm/main/qualiclip_gpu_inv_multi_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn qualiclip --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --reward_fn qualiclip --evil_twin


sbatch -J=ir --err=slurm/main/ir_cpu.err --out=slurm/main/ir_cpu.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --evil_twin
sbatch -J=ir --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/ir_gpu.err --out=slurm/main/ir_gpu.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --evil_twin

sbatch -J=ir --err=slurm/main/ir_cpu_inv.err --out=slurm/main/ir_cpu_inv.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --evil_twin
sbatch -J=ir --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/ir_gpu_inv.err --out=slurm/main/ir_gpu_inv.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --evil_twin

sbatch -J=ir --err=slurm/main/ir_cpu_inv_multi.err --out=slurm/main/ir_cpu_inv_multi.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --evil_twin
sbatch -J=ir --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/ir_gpu_inv_multi.err --out=slurm/main/ir_gpu_inv_multi.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --evil_twin


sbatch -J=ir --err=slurm/main/ir_cpu_inv_pp.err --out=slurm/main/ir_cpu_inv_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --evil_twin
sbatch -J=ir --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/ir_gpu_inv_pp.err --out=slurm/main/ir_gpu_inv_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --use_pplus --evil_twin

sbatch -J=ir --err=slurm/main/ir_cpu_inv_multi_pp.err --out=slurm/main/ir_cpu_inv_multi_pp.out runpymain.sh main_ir.py --style_layers_train --epochs 1   --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --evil_twin
sbatch -J=ir --exclude=gpu[005,006,011,012],cuda[001,002] --err=slurm/main/ir_gpu_inv_multi_pp.err --out=slurm/main/ir_gpu_inv_multi_pp.out runpygpu.sh main_ir.py --style_layers_train --epochs 1 --gradient_accumulation_steps 1 --sample_num_batches_per_epoch 2 --mixed_precision bf16 --batch_size 1 --project_name style_test --reward_fn ir --style_layers_train --style_mid_block --prompt_src_txt random_animals.txt --textual_inversion --num_vectors 3 --use_pplus --evil_twin
