_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 83
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 83
                - 98
            "3":
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
dest_dataset:
    value: jlbaker361/destination-embedding
dino_pooling_stride:
    value: 4
embedding:
    value: ssl
facet:
    value: query
limit:
    value: 2
mixed_precision:
    value: "no"
project_name:
    value: directional
src_dataset:
    value: jlbaker361/directional
