_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 49
                - 51
                - 55
                - 71
            "3":
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
dataset_list:
    value:
        - jlbaker361/tfi2i-dreambooth
        - jlbaker361/rect-dreambooth
        - jlbaker361/masa-dreambooth
figure_name:
    value: fig
limit:
    value: -1
mixed_precision:
    value: "no"
project_name:
    value: evaluation-creative
